Repository React-Native-Camp/privateTeacher, pull requests merged in 2020-12, with the labels that each got.

#38 Student profile
  client/package.json
  client/src/App.js
  client/src/actions/studenAction.js
  client/src/actions/types.js
  client/src/assets/default-avatar.jpg
  client/src/components/PersonCard/index.js
  client/src/components/screens/AuthScreen/StudentProfile.js
  client/src/reducers/studentReducer.js
  client/src/store.js
Labels: Review

#40 add course for teacher
  client/package.json
  client/src/App.js
  client/src/actions/courseAction.js
  client/src/actions/types.js
  client/src/components/screens/MainScreen/AddCourse.js
  client/src/components/screens/MainScreen/AddCourse/AddCourse.js
  client/src/components/screens/MainScreen/AddCourse/Schedule.js
  client/src/reducers/courseReducer.js
Labels: inProgress

#46 display student course
  client/src/App.js
  client/src/components/PersonCard/index.js
  client/src/components/screens/AuthScreen/StudentCourse.js
  client/src/reducers/courseReducer.js
Labels: Review

#41 teacher profile #19
  client/src/App.js
  client/src/components/screens/AuthScreen/TeacheProfile.js
Labels: in progress

#47 Teacher's course
  client/src/App.js
  client/src/actions/courseAction.js
  client/src/actions/types.js
  client/src/components/screens/AuthScreen/TeacherCourses.js
  client/src/reducers/courseReducer.js
Labels: Review
